# Generated by Django 5.0 on 2023-12-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=13)),
                ('git_url', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedIn_url', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
    ]
